### ISSUE TITLE
HOLY SHIT THIS GAME CRASHES ALOT

### ISSUE THREAD

**Issue by Borists1** [Leather128/LeatherEngine#111]
when i do anything the game crashes

for example turning on a mod

pausing a song from freeplay

and much more

**Comment by Leather128** [comment]
are you running 64 bit or 32 bit?

**Comment by SrtHero278** [comment]
> are you running 64 bit or 32 bit?

I have this issue too.
I'm using an `action build`.

**Comment by Leather128** [comment]
> > are you running 64 bit or 32 bit?
> 
> I have this issue too. I'm using an `action build`.

and your computer is 64 bit right? because action builds dont have 32 bit versions yet.

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/147854076-b2c6f476-d7d7-4905-8ad1-3f05d3359bb6.png)

**Comment by Leather128** [comment]
how much ram/memory do you have?

**Comment by MemTheBun** [comment]
8GB

**Comment by Leather128** [comment]
> 8GB

wait you're having this issue too?

**Comment by boristsve** [comment]
@Leather128 sorry for not responding.

I have 64bit

**Comment by Borists1** [comment]
> are you running 64 bit or 32 bit?

64bit
