### ISSUE TITLE
Bug Report: Game Crashes at random times

### ISSUE THREAD

**Issue by RealFazzyGames** [Leather128/LeatherEngine#12]
when i pause the game or go to the mods menu to the settings menu or going from the settings to the mods menu it crashes

**Comment by Leather128** [comment]
question: what are your settings and what operating system are you using? (currently the game only supports windows x64 natively so I would like to know just in-case this is compatibility issues).

**Comment by RealFazzyGames** [comment]
> question: what are your settings and what operating system are you using? (currently the game only supports windows x64 natively so I would like to know just in-case this is compatibility issues).

basically the default and i use windows 10 x64

**Comment by Leather128** [comment]
ok another question: are you building the game yourself? or are you using the release builds?

**Comment by RealFazzyGames** [comment]
> ok another question: are you building the game yourself? or are you using the release builds?

i use the release builds

**Comment by Leather128** [comment]
You are using the most recent build right?

**Comment by RealFazzyGames** [comment]
yeah 0.3.2 then 0.3.3

**Comment by Leather128** [comment]
do you have any idea what might be causing this to happen? (because at this point, i've got no clue since this problem doesnt seem to be happening for anyone else)

**Comment by Leather128** [comment]
could u possibly give computer specs just in case its something to do with your pc's hardware?
