### ISSUE TITLE
Enhancement: Some feature ideas for your engine.

### ISSUE THREAD

**Issue by ghost** [Leather128/LeatherEngine#124]
Hey Leather, I love your engine so much and it is easy for me to make mods.

So I had an idea for a new feature in your engine.

(The feature is from the fnf Mic'd Up mechanic [1-2]).

1.Chart Types

~Flip: The Flip is for Player or opponent to becomes flipped the note, similarly to B-sides' flip difficulty but with the opponent.
~Chaos:The Chaos to all arrows on the chart become randomized,without a way to know what is coming next.
~One Arrow: The One Arrow is for All arrows are placed on one arrow lane out of four, chosen randomly.
~Stair:The Stair is for All notes represent a stair-like pattern, going from left side, to right side, and then repeating until the end of a song.
~Wave:The Ware is for All notes represent a wave-like pattern, going from left side, to right side, and then to left side.

2.Mode
~Endless: The Endless is for playing the song over and over again (but with how many loops you want).

3.Tools
  -Animation debug
     ~Flip: is for making a boyfriend.

4.New Feature
~Hitsound in game:this is what i want in your engine to hit the note with sounds like OSU! or Dave and Bambi, aslo with custom sounds.
~Practice Mode:this is used for practice in the game, you can't die and you can't save the score when the song is fishing.

And that all
but if you can't to all then is ok.

**Comment by Leather128** [comment]
Ok, I don't really wanna add the chart types and endless mode but uh...

Animation debug already exists,
I'm making a character creator at some point already,
Hitsounds are already in,
and Practice Mode is also already in (no death option)

(keep in mind, these things are in most recent code and builds, not releases)

**Comment by ghost** [comment]
ok thx
