### ISSUE TITLE
Some bottom text is behind the screen, in Freeplay

### ISSUE THREAD

**Issue by TheLeerName** [Leather128/LeatherEngine#128]
`speed` is behind the screen, btw few pixels of it are visible. Try do less scale of text.

![kwG4ds0n0A](https://user-images.githubusercontent.com/85291330/148652446-9db05066-415d-4eae-9ac3-054f81608aba.png)

![Ftq6bhCJsT](https://user-images.githubusercontent.com/85291330/148652565-28ace73a-337a-4242-b531-4e4c2f6d5ea0.png)

**Comment by Leather128** [comment]
will fix

**Comment by Leather128** [comment]
fixed in b8e32ec
