### ISSUE TITLE
Enhancement: Custom boyfriend death animation, custom death sound and custom game over music in to mods folder

### ISSUE THREAD

**Issue by ghost** [Leather128/LeatherEngine#134]
Hey it's me again
So I want to make a custom boyfriend death animation, custom death sound and custom game over (gameOver.ogg and gameOverEnd.ogg) music to the mods folder because I want to make the same animation to the skin or the same connection to the stage in the game.

like example:

1.Boyfriend_Assets > fnf_loss_sfx > Boyfriend_Dead_Assets > gameOver.ogg > gameOverEnd.ogg

2.bfCar > fnf_loss_sfx > Boyfriend_Dead_Assets > gameOver.ogg > gameOverEnd.ogg

3.bfChristmas > fnf_loss_sfx > Boyfriend_Dead_Assets > gameOver.ogg > gameOverEnd.ogg

4.bfPixel > fnf_loss_sfx-pixel > bfPixelsDEAD > gameOver-pixel.ogg > gameOverEnd-pixel.ogg

the 1-4 have the same death sanimation death sound and game over music, but the number 5 is different because it has [pixel].

so that i want to make a bf death to mods folder like this: 
[custom character] >[ custom sfx] >[ custom dead] > [custom game over] > [custom game over end]

So can you add custom death, custom death sound and custom game over in to mods folder?

**Comment by Leather128** [comment]
custom death animation is already a thing `deathCharacterName` option, but the rest i will add

**Comment by Leather128** [comment]
added in b5f71c8df76b58b7e1e2a8178fc97a9ff9d8d897 (although this a bit different to what you suggested, basically each death character has different sounds in the files relating to their character name)
