### ISSUE TITLE
Enhancement: Stealth Mod

### ISSUE THREAD

**Issue by daisukidaisy** [Leather128/LeatherEngine#137]
This should be simple to implement.
In DDR or StepMania, Stealth Mode means you can't see the notes moving towards the strum line, and you must play the chart by memory. Basically, just make the moving notes invisible.

**Comment by Leather128** [comment]
seems easy enough, will add after im done rewriting all the options code

**Comment by Leather128** [comment]
added in 24e948625a2baaa818cf1beb2670c9c44e08ecbf
