### ISSUE TITLE
Trying to open charting state with custom modding framework crashes the game

### ISSUE THREAD

**Issue by bdidk235** [Leather128/LeatherEngine#140]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.4.1 with custom-mod-framework branch

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Play a song (from a mod)
2. Press 7 

## Please describe your issue. Provide extensive detail and images if possible.
I was testing random stuff on the custom modding framework!

**Comment by Leather128** [comment]
yea custom modding framework is a bit unstable rn so yea will prolly be fixed when it's all done (also thx for actually using the bug report template unlike pretty much everyone else)
