### ISSUE TITLE
Enhancement: Better audio-to-difficulty system

### ISSUE THREAD

**Issue by daisukidaisy** [Leather128/LeatherEngine#153]
### What's currently there
"Inst-foo" and "Voices-bar" will correspond to "FOO" and "BAR" difficulties respectively. You currently cannot have two difficulties use the special audio files without duplicating them under different names.
### A helpful addition
A line in the .json file that itself determines which Inst and Voices files are used. That way, there can be multiple difficulties that use the audio files labeled with "ERECT" or "GODMODE" difficulty, for example, if need be.

**Comment by bdidk235** [comment]
I think that actually already exists by looking at the code, tell me if I got something wrong.

**Comment by Leather128** [comment]
sounds good

**Comment by Leather128** [comment]
added in be8cf95 with the `specialAudioName` property in song.json file (nothing in charting state yet but yes)
