### ISSUE TITLE
help

### ISSUE THREAD

**Issue by MrFrostHacker** [Leather128/LeatherEngine#155]
it work but says this
Compiling group: native-discord-rpc
cl.exe -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/lib/discord-rpc/include/ -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/lib/rapidjson/include/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -Od(optim-std) -Zi(optim-std) -FdC:\Users\admin\Desktop\GAMES FOR PC\Leather Engine Build\LeatherEngine-main\export\debug\windows\obj\obj/msvc1964-debug-nc/vc.pdb(optim-std) -Zi(debug) -FdC:\Users\admin\Desktop\GAMES FOR PC\Leather Engine Build\LeatherEngine-main\export\debug\windows\obj\obj/msvc1964-debug-nc/vc.pdb(debug) -Od(debug) -O2(release) -bigobj -Os(optim-size) -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - C:/HaxeToolkit/haxe/lib/discord_rpc/git/lib/discord-rpc/src/discord-rpc.cpp
Error: discord-rpc.cpp
C:\HaxeToolkit\haxe\lib\discord_rpc\git\lib\rapidjson\include\rapidjson/document.h(20): fatal error C1083: Cannot open include file: 'reader.h': No such file or directory

**Comment by MrFrostHacker** [comment]
pls help me

**Comment by Leather128** [comment]
try redownloading the source code and to run [this file](https://github.com/Leather128/LeatherEngine/blob/main/building/install_libraries.bat) before trying another build, btw what haxe version do you have?
