### ISSUE TITLE
Bug Report: I fixed gf pixel offsets cuz she broke

### ISSUE THREAD

**Issue by ghost** [Leather128/LeatherEngine#157]
Fixed gf pixel offsets:
[offsets.txt](https://github.com/Leather128/LeatherEngine/files/7918798/offsets.txt)

**Comment by Leather128** [comment]
NOOOOO we don't do that.. im sorry but we ***DON'T JUST MAKE CHARACTER OFFSETS IN THE ANIM OFFSETS*** also im working on fixing that cuz ik how to and it's ez lol so yeah
