### ISSUE TITLE
Bug Report: Downloaded latest build, crashed upon loading MILF (and my modded songs)

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#168]
## What version of the game are you using?
0.4.1. I got the build from the Actions page, latest commit.

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
When I started my modded song from 0.4.0, and later MILF,  the game crashed and displayed this error message.

## Please describe your issue. Provide extensive detail and images if possible.
![image](https://user-images.githubusercontent.com/25996506/152228744-1e0c7bd3-7854-4cbf-8a72-ea1436e27c9b.png)
I cannot provide more detail as I'm not sure why this occurred.

**Comment by Leather128** [comment]
so you got it from [this page](https://github.com/Leather128/LeatherEngine/actions/runs/1780664808) right?

**Comment by JordanSantiagoYT** [comment]
i tried with older action build - works, however modchart compatibility is broken

**Comment by Onemario1234** [comment]
> so you got it from [this page](https://github.com/Leather128/LeatherEngine/actions/runs/1780664808) right?

Yes I did.

**Comment by Leather128** [comment]
well modded songs (even with modcharts) seem to work fine for me, you guys are running 64 bit not 32 bit right?

**Comment by JordanSantiagoYT** [comment]
yeah, i was using the linux stuff update action build

**Comment by Onemario1234** [comment]
I assume so. My only option was "WindowsBuild"

**Comment by JordanSantiagoYT** [comment]
ok, using the latest action build didnt work, modcharts still don't work. unless the way of enabling modcharts changed

**Comment by JordanSantiagoYT** [comment]
update: just found out maybe health drain doesnt work on modcharts anymore as i tried a different modchart which did stuff and it worked

**Comment by Leather128** [comment]
could you possibly try [this actions build](https://github.com/Leather128/LeatherEngine/actions/runs/1789980699) (once it's done) and see if it fixes it? it seems to work perfectly fine for me (yes I'm using my self compiled version but it should work the same)

**Comment by Leather128** [comment]
> update: just found out maybe health drain doesnt work on modcharts anymore as i tried a different modchart which did stuff and it worked

what health drain modchart are you using? im using this one:
```lua
function start(song)
    print(song)
end

function playerTwoSing(data, time, type)
    if getHealth() - 0.035 > 0 then
        setHealth(getHealth() - 0.035)
    else
        setHealth(0.035)
    end
end
```
and it works perfectly fine as of commit 67ba06121ac8c4e9f0972cce01c59f6c33cabafe

**Comment by JordanSantiagoYT** [comment]
oh, im using this one: 

function update (elapsed) -- example https://twitter.com/KadeDeveloper/status/1382178179184422918
	local currentBeat = (songPos / 1000) * (bpm / 60)

function playerTwoSing(noteDirection, songPosition, arrowType)
      if currentBeat >= 288 and currentBeat < 353 then
           setProperty('health', getProperty('health') - 0.0225);
      end
      if currentBeat >= 656 and currentBeat < 720 then
           setProperty('health', getProperty('health') - 0.025);
      end
end

function playerTwoSingHeld(noteDirection, songPosition, arrowType)
      if currentBeat >= 288 and currentBeat < 353 then
           setProperty('health', getProperty('health') - 0.0225);
      end
      if currentBeat >= 656 and currentBeat < 720 then
           setProperty('health', getProperty('health') - 0.0225);
      end
end
end

**Comment by JordanSantiagoYT** [comment]
okay, so update: i tried your health drain modchart and it worked, i guess mine was outdated then

**Comment by Leather128** [comment]
yeah i guess that happens sometimes

**Comment by Onemario1234** [comment]
Yep, just updated to the latest build, everything works good now.
