### ISSUE TITLE
Bug Report: Notes that are copied and pasted aren't appearing

### ISSUE THREAD

**Issue by ScratchRZL** [Leather128/LeatherEngine#174]
when i copy and paste a section it doesn't show up when playing the song and i have to manually re-place each pasted note

**Comment by Leather128** [comment]
it seems to work fine for me, you are going to a section, pressing 'copy section' then going to the section to paste on, and pressing 'paste section' right?

**Comment by ScratchRZL** [comment]
yeah

**Comment by ScratchRZL** [comment]
the notes are there in the chart editor but when i actually play the chart they don't appear

**Comment by Leather128** [comment]
weird

**Comment by Leather128** [comment]
this bug has been fixed now (not in latest commit since it's not published yet, but yeah)

**Comment by ScratchRZL** [comment]
thank you leather
