### ISSUE TITLE
Mods menu doesnt appear on html5 exports of LE 0.4.1

### ISSUE THREAD

**Issue by NotSorena** [Leather128/LeatherEngine#178]
Damn.
![image](https://user-images.githubusercontent.com/89949310/153722286-d87f6e23-ac42-4be4-87fe-165aa06d218c.png)

**Comment by Leather128** [comment]
cuz it doesn't support mods

**Comment by NotSorena** [comment]
why does the mods folder export though if it has no use on html5
is it even possible to make the mods folder have use in html5 exports??
i need this for my games website dude

**Comment by Leather128** [comment]
> why does the mods folder export though if it has no use on html5 is it even possible to make the mods folder have use in html5 exports?? i need this for my games website dude

just put the assets for the mods in base assets (well besides _append stuff which you just put the contents of below the regular file's stuff) but yeah

**Comment by NotSorena** [comment]
alright, thanks.
will try later.
