### ISSUE TITLE
Bug Report: version.txt says 0.4.0 and not 0.4.1

### ISSUE THREAD

**Issue by Vortex2Oblivion** [Leather128/LeatherEngine#184]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Leather128** [comment]
it's not a bug, it's a thing that isn't changed yet because i only change it when a new release is made you fard

**Comment by Vortex2Oblivion** [comment]
stfu leather

**Comment by Leather128** [comment]
lol

**Comment by NotSorena** [comment]
lol
