### ISSUE TITLE
Enhancement: The double color in Health Bar

### ISSUE THREAD

**Issue by ghost** [Leather128/LeatherEngine#187]
_Hello again,_ 
I would like to tell you to add a double color bar

because i want to have the same icon color

### like example:
Skid & Pump they have the different color:
Skid is gray
Pump is orange.

and i want you to half color like this

![a](https://user-images.githubusercontent.com/87716423/155238005-5e1cf758-20ec-4194-87b6-eeb4ce8c2ed2.png)

so that i want to add to your engine.
thx

**Comment by Leather128** [comment]
but how do i do that

**Comment by ghost** [comment]
Well if i remember correctly, there is a new engine (idk what name and i trying to find it but i can’t find it, I think they delete the engine)
There are new things like a new ui health bar, new icon and double color bar.

**Comment by ghost** [comment]
but you can not to add if you want

**Comment by Leather128** [comment]
i mean it's a cool idea i just don't know how to add it

**Comment by thatsacrylic** [comment]
maybe creating a second color "bar" in case the double color option is used? i don't really know but that's my guess

**Comment by ghost** [comment]
you could add two healthbars with different color
