### ISSUE TITLE
Bug Report: Modcharts don't seem to get recognized on the latest commit build (this should fix freeplay music?)

### ISSUE THREAD

**Issue by thatsacrylic** [Leather128/LeatherEngine#202]
Note: I am using the Github Actions version of the builds.

**Comment by Leather128** [comment]
what modcharts are you using, and where are you putting them?

**Comment by thatsacrylic** [comment]
I am putting them in mods/*my mod*/data/modcharts.
The modchart i am using is this health drain modchart:

```lua
function start(song)
    print(song)
end

function playerTwoSing(data, time, type)
    if getHealth() - 0.035 > 0 then
        setHealth(getHealth() - 0.035)
    else
        setHealth(0.035)
    end
 end

**Comment by thatsacrylic** [comment]
I have also tried some simple modcharts like a screen rotate modchart.
