### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by bobmario123** [Leather128/LeatherEngine#209]
When I go into charting mode the arrows in the graph will turn into black boxes, along side this when you exit chating mode GF's sprite will turn into a black box and sometimes the game crashes I use the 32X version.

**Comment by JadenMudge** [comment]
same happens to me, on the 64X version.
just save the chart and re-open the game.
idk what you do with the GF Sprite thing.

**Comment by Leather128** [comment]
for the gf sprite thing, prob wanna turn on 'Optimized Characters' in Options > Graphics > Optimizations (because that problem is probably caused by low memory)
the arrows thing can be fixed by just reloading the ui skin
idk why game would crash tho
