### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by TheAngelHosko** [Leather128/LeatherEngine#210]
Help, when i compile the leather engine this appears: **source/modding/CharacterCreationState.hx:282: characters 42-53 : flixel.animation.FlxAnimationController has no field getNameList**

**Comment by Leather128** [comment]
update your flixel with `haxelib update flixel` in cmd/terminal

**Comment by TheAngelHosko** [comment]
Now this appears : Failed - try fixing the error(s) and restarting the language server:

source/states/PlayState.hx:3: characters 8-25 : You cannot access the cpp package while targeting js (for cpp.NativeProcess)
source/utilities/CoolUtil.hx:4: characters 8-24 : ... referenced here
source/substates/OutdatedSubState.hx:4: characters 8-26 : ... referenced here
source/states/TitleState.hx:9: characters 8-34 : ... referenced here
source/Main.hx:7: characters 8-25 : ... referenced here

**Comment by Leather128** [comment]
uh what platform are you trying to build on?

**Comment by TheAngelHosko** [comment]
Visual studio code

**Comment by Leather128** [comment]
no i mean like 'windows' or 'html5' ***not the code editor you're using***

**Comment by TheAngelHosko** [comment]
Windows
