### ISSUE TITLE
Enhancement: middlescroll global variable

### ISSUE THREAD

**Issue by flowerbearttv** [Leather128/LeatherEngine#218]
Title is self-explanatory, mod charts should have a middle scroll global variable or outright disable middlescroll if a modchart is undetected,
mainly cause middle scroll moves your arrows to the center and modcharts could break as a result

**Comment by Leather128** [comment]
done in [2d4b3a7](https://github.com/Leather128/LeatherEngine/commit/2d4b3a7d293301273eab9a7850b93afd38ad7002)
