### ISSUE TITLE
Bug Report: i cant compile the game cuz source/modding/PolymodHandler.hx:14: lines 14-28 : { modRoot : String, frameworkParams : { assetLibraryPaths : haxe.ds.Map<String, String> }, errorCallback : Null<(error : polymod.PolymodError) -> V... has extra field frameworkParams source/modding/PolymodHandler.hx:14: lines 14-28 : For function argument 'params'

### ISSUE THREAD

**Issue by nbn7272** [Leather128/LeatherEngine#22]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Leather128** [comment]
repeat of issue #19, just follow what i said in it and you should be good.
