### ISSUE TITLE
Bug Report: Sprites not loading

### ISSUE THREAD

**Issue by RhysRJJ** [Leather128/LeatherEngine#222]
![image_2022-03-21_042107](https://user-images.githubusercontent.com/102009519/159205050-e9f44502-3da7-4eb9-a4f5-41831cd2757d.png)

![image_2022-03-21_042253](https://user-images.githubusercontent.com/102009519/159205150-128cde72-3c6b-49d9-ad69-337703b12e98.png)

On version 0.4.1 I've had multiple sprites load in as just a black box, and then if I try to do anything like go to a different song the engine would crash. This has happened with gf, bf, and a few shaggy's. I've tried quite a few things to fix it but it doesn't seem to work and it would just cause another crash, it would be great if I could get an answer on how to fix this since it's rather annoying

And here are some screenshots of the config files:
![image_2022-03-21_042949](https://user-images.githubusercontent.com/102009519/159205612-d69b16f1-9d91-425a-87f8-177724eba4b7.png)

![image_2022-03-21_042923](https://user-images.githubusercontent.com/102009519/159205592-231eb885-8577-4238-aea2-c1fcd1d3aa03.png)

**Comment by Leather128** [comment]
how much memory does your computer have?

**Comment by RhysRJJ** [comment]
> how much memory does your computer have?

I have 8gb

**Comment by Leather128** [comment]
weird
