### ISSUE TITLE
Question: How to make custom Title screen?

### ISSUE THREAD

**Issue by JealousHateBoy** [Leather128/LeatherEngine#223]
Okay so I've tried in my mod to replace title screen on something different. The main problem is in dancing gf which ive tried to replace. When i did that my "dancing gf" sprite just added in a really weird way and i dont know how to fix offsets. If anyone knows how to fix it please help.
![Безымянный](https://user-images.githubusercontent.com/102369425/160136546-4d464bee-7621-48f4-80a6-b8645c5fc365.png)
(i neeed to tweak matt on right)

**Comment by Vortex2Oblivion** [comment]
i dont think you can change that without editing source or making a new spritesheet.

**Comment by Squidtito** [comment]
> i dont think you can change that without editing source or making a new spritesheet.

Changing the sprite sheet wouldn't have any effect since the generated sprite sheet is always centered
