### ISSUE TITLE
how to add new characters?

### ISSUE THREAD

**Issue by PHGaming121** [Leather128/LeatherEngine#23]
how to add new characters?

**Comment by PHGaming121** [comment]
I've already put the .xml file, sprites and the offsets.txt and config.json files but... when I enter freeplay and choose my mod music (easy normal or hard) the game crashes without error message or anything

**Comment by PHGaming121** [comment]
Please anyone who knows how to resolve this reply as soon as they see this message

**Comment by Leather128** [comment]
are you sure the song isn't partially the problem? it could be something in the song (like a stage, or other character) is missing / not implemented, causing the game to crash (usually a missing character, but it could be something else).

**Comment by Leather128** [comment]
also make sure your character has health icons

**Comment by PHGaming121** [comment]
it's not the music that's missing but the character that I'm not sure how to add it to the game and play the music with my custom character...

**Comment by PHGaming121** [comment]
and yes, it has health icons

**Comment by PHGaming121** [comment]
So... basically what I did was change the characters in the song 
Example: 
player1: "bf" 
player2: "MY CHARACTER" 
but when selecting the song in freeplay, the game crashes and closes without error messages 
Can someone help me? 
Would it be an error in some code? 
Anything in the .json file for the song? 
Please, as soon as you know the answer, answer here.

**Comment by Leather128** [comment]
question: did you import the chart from psych engine? (or any engine with arrow types?)

**Comment by Leather128** [comment]
because i know from experience, songs from psych or other engines with arrow types can have malformed notes that leather engine cannot process properly

**Comment by PHGaming121** [comment]
Yes!!! I used psych engine to Make my mod!!!
It worked

**Comment by Leather128** [comment]
nice
