### ISSUE TITLE
Bug Report: Crash when entering a song, the button A is not working, please fix it and this will be a good port

### ISSUE THREAD

**Issue by DJjoteeYT** [Leather128/LeatherEngine#237]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by DJjoteeYT** [comment]
Error description: Invalid Char 47 at Position 0

**Comment by Leather128** [comment]
what are you even talking about

**Comment by Leather128** [comment]
more context please?
