### ISSUE TITLE
Bug Report: extra miss without really missing

### ISSUE THREAD

**Issue by victor176S** [Leather128/LeatherEngine#243]
i play on Windows 10 (`x86_64`)

leather engine 0.4.1

the game goes good in my pc (300fps) so this is not a factor of the bug

my keyboard is 4-key rollover, so it isn´t that neither, (and i have it with the keys of the video so there isn´t blocking key)

the bug happens sometimes when i have to press more than one note at once, and it gives me a miss of nowhere, in the video i show my configuration and in the title is the minute of the bug
[https://www.youtube.com/watch?v=4_5C1DgyOqY](url)

**Comment by Leather128** [comment]
what i think is really happening is your keyboard has 4-key rollover, which means that it... hear me out... *sometimes doesn't detect key presses if you do too many at once*, so i feel as if this is less an engine problem or bug report, and more a hardware issue + also the fact you seem to be missing a lot anyways + we don't know if you have rhythm mode on as your input mode (as that was never shown in the video), so yeah
