### ISSUE TITLE
Bug Report: Mods

### ISSUE THREAD

**Issue by Flamgeo** [Leather128/LeatherEngine#245]
i play on Windows 10 (x86_64)

leather engine 0.4.1

So basically im trying to import a mod into the mod file but every time i start up the game, i try to enable the mods, then it crashes before i could do anything. Is there something im doing wrong. If you have an answer to this pls.

**Comment by Leather128** [comment]
1st. What mod is it?
2nd. This is the most recent release right, not source?

**Comment by Flamgeo** [comment]
No source being used
Yes its the most recent

The mods:
https://github.com/Leather128/LeathersFNFModPorts

**Comment by Vortex2Oblivion** [comment]
try going to C:\Users\username\AppData\Roaming and delete the folder called "leather128"
