### ISSUE TITLE
Bug Report: Icons - Check, Character - Nothing?

### ISSUE THREAD

**Issue by sanamasako** [Leather128/LeatherEngine#248]
So I'm porting the Miku mod. I got all the characters and stages, and the songs and charts. Right?
I go to open Loid, and, along with the stage not working (concert on Loid, voca for Voca, then Expo which actually CRASHES the game for some reason), Miku appears as BF even though her icon shows in the chart editor. I'm confused as hell right now. Did I do something wrong or is LE being retarded, because I really don't see how a character's icon can load properly and then have a brainfart and replace itself with Boyfriend.

**Comment by Leather128** [comment]
you are doing stuff wrong

**Comment by Leather128** [comment]
if a character loads as bf, that means the game couldn't find the character

**Comment by Leather128** [comment]
so

**Comment by Leather128** [comment]
you put the character config in the wrong place basically

**Comment by sanamasako** [comment]
So you're saying characters' spritesheets and XMLs _don't_ go in shared/images/characters of the mod? And, you're saying their jsons _don't_ go in data/character data of the mod? What about stages, which the OG Miku mod doesn't have jsons of? The stage editor doesn't let me create jsons out of the images, it's just a "move the characters and save" kind of thing.

**Comment by Leather128** [comment]
Well
1st. Characters spritesheets do go there
2nd. Character jsons go in `data/character data/[insert character name here]/` not just `data/character data/`
3rd. For stages, you kinda just make them in json and use the stage editor to edit sprite positions at the moment (stage editor is literally under the **`wip`** tools section)

Also just remember, Leather Engine uses custom json formats for everything besides songs pretty much (aka if character jsons or stage jsons exist in mods that aren't in LE, they won't work)

**Comment by sanamasako** [comment]
Oh god. Well then, I'm looking forward to Stage Editor's completion because coding things in json doesn't work for me lol.

**Comment by Leather128** [comment]
how does it not work for you?

**Comment by sanamasako** [comment]
I try entering the details image-by-image, even if it means copying code from other jsons and tweaking it to what I need, and it just doesn't work. The stage editor gives me some shit about "invalid characters" at a random line, then gives me the finger and crashes. 🤷‍♀️
