### ISSUE TITLE
Bug Report: Play Animation event not working fully

### ISSUE THREAD

**Issue by RhysRJJ** [Leather128/LeatherEngine#250]
So pretty much, it seems like the playanimation events are based on a songs bpm, causing them to play for less time/frames on higher bpm songs

https://streamable.com/joths3
At the end his detrans animation should play slowly like in the og mod but it plays for a couple frames before stopping, I have no idea if there's a fix for this or a way around it but yea, sorta sucks lmao

Hopefully this all makes sense

**Comment by Leather128** [comment]
basically what you do is use the "character will idle" the event to make the character not idle until you want them to idle (aka u set them to be able to idle when you want) and yes, while this is annoying it will work until i actually make it work without doing that
