### ISSUE TITLE
Bug Report: Currently running 0.4.2, latest version 0.4.2

### ISSUE THREAD

**Issue by sanamasako** [Leather128/LeatherEngine#252]
![image](https://user-images.githubusercontent.com/53914467/173710802-71072b1f-cb67-43cc-923b-9264c2f64140.png)
Oh, okay.
Yeah I just got 0.4.2 and it's saying it's outdated even though it came out 2 hours ago lol.

**Comment by swordcube** [comment]
The version number on github doesn't immediately change when a new update releases, so this ends up happening until the version number on github gets updated

**Comment by Leather128** [comment]
yeah this doesn't happen anymore, we good fam
