### ISSUE TITLE
Bug Report: MusicBeat, ModsMenu, and CharacterCreatorState not working correctly while building

### ISSUE THREAD

**Issue by MapidsFanAnimator** [Leather128/LeatherEngine#253]
source/states/MusicBeatState.hx:35: characters 19-29 : Class<polymod.Polymod> has no field clearCache
source/states/ModsMenu.hx:164: characters 139-146 : Null<polymod.ModMetadata> has no field _author (Suggestion: author)
source/modding/CharacterCreationState.hx:325: characters 46-57 : flixel.animation.FlxAnimationController has no field getNameList

**Comment by Leather128** [comment]
1. If you encounter errors like this again, please try reading the actual Build.md file first
2. Run these commands to fix the errors:
```
haxelib install polymod 1.5.2
haxelib update flixel
```
and you should be good :+1:
