### ISSUE TITLE
Enhancement: make the note snap thing zoom in/out like psych engine

### ISSUE THREAD

**Issue by ScratchRZL** [Leather128/LeatherEngine#254]
the more precise note snap options are almost impossible to use without it

also i wanna win an argument with someone i dont like so :trollface:

**Comment by Leather128** [comment]
could've just said 'add a zoom option', but ok fine i'll add a stupid zoom option to the charter

**Comment by Leather128** [comment]
[b45f351](https://github.com/Leather128/LeatherEngine/commit/b45f35118560a093fc9200dabaf9ee5c7ec6279a)
