### ISSUE TITLE
Offsets not saving/resetting to a default version

### ISSUE THREAD

**Issue by RhysRJJ** [Leather128/LeatherEngine#256]
Another thing I've run into at times is the offsets for a character not saving and seeming to default to something else, mostly happens with bfs whenever I try adding more

**Comment by Leather128** [comment]
you press the save offsets button and save it to their offsets.txt file right?

**Comment by RhysRJJ** [comment]
Yep, I've even tried saving a second version somewhere else and checking if the main one changes afterwards but it stays the same. It seems like it has some sorta default version that overlaps the edited one or something

**Comment by Leather128** [comment]
well that might be because the character you're using is set to be default flip x, try turning off that setting, making offsets, and then turning it back on to see if that helps?

**Comment by RhysRJJ** [comment]
That worked, thanks for the help
