### ISSUE TITLE
Bug Report: Every time I pause my game crashes

### ISSUE THREAD

**Issue by Randomllyin** [Leather128/LeatherEngine#258]
It's pretty self-explanatory. Playing on Windows X64, and I haven't edited the source code.

**Comment by Leather128** [comment]
can you see if the most recent commits ([2820b55](https://github.com/Leather128/LeatherEngine/commit/2820b55206de131a80bc18139be4e67a12439144)) fixed it for you? (if they didn't, reopen this issue i guess)
