### ISSUE TITLE
Enhancement: Modifiable judgement timings

### ISSUE THREAD

**Issue by daisukidaisy** [Leather128/LeatherEngine#26]
The base judgement timings are strange compared to that of other engines. I'd like to see something similar to Safe Frames implemented, if not full customization.

**Comment by Leather128** [comment]
ok lemme do that

**Comment by Leather128** [comment]
available as of commit [450b3e4](https://github.com/Leather128/LeatherEngine/commit/450b3e46b827d6f57aa7269aaf3ca402d18a4a13)
