### ISSUE TITLE
Bug Report: CurStep & CurBeat Glitch

### ISSUE THREAD

**Issue by Unkrown6YT** [Leather128/LeatherEngine#262]
CurStep & CurBeat is having a Glitch
While holding W in chart editor
Here is a screen shot
![bug](https://user-images.githubusercontent.com/94491221/176489392-42f438eb-bfad-4a11-b6f3-1ccc3485c3bf.png)

**Comment by Leather128** [comment]
oh yeah that's because the song position is negative, so of course the song beat and stuff is negative, what did you expect?

**Comment by Leather128** [comment]
also that doesn't even really effect the game at all, but i'll fix it anyways lol
