### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by Unkrown6YT** [Leather128/LeatherEngine#263]
Add 19, 20, 21, 22, 23 & 24 keys please

**Comment by Leather128** [comment]
add it yourself

**Comment by Unkrown6YT** [comment]
Sorry, I'm too lazy to add 19+ keys with source code :(

**Comment by Unkrown6YT** [comment]
Add it yourself right now @Leather128

**Comment by Unkrown6YT** [comment]
Source Code is hard for me :(

**Comment by Leather128** [comment]
it's with text files, not source code |:/
