### ISSUE TITLE
Made 19, 20, 21

### ISSUE THREAD

**Issue by Unkrown6YT** [Leather128/LeatherEngine#264]
[maniaAnimationDirections.txt](https://github.com/Leather128/LeatherEngine/files/9037982/maniaAnimationDirections.txt)
[maniaCharacterAnimations.txt](https://github.com/Leather128/LeatherEngine/files/9037983/maniaCharacterAnimations.txt)
[maniaDirections.txt](https://github.com/Leather128/LeatherEngine/files/9037984/maniaDirections.txt)
[defaultBinds.txt](https://github.com/Leather128/LeatherEngine/files/9037985/defaultBinds.txt)

When you will add to your engine @Leather128 ?

**Comment by Leather128** [comment]
made my own (up to 21 not 23) in [2dfbc35](https://github.com/Leather128/LeatherEngine/commit/2dfbc358b09a2c36d141a6840ef19f4b139bc6cc), so nah

**Comment by Leather128** [comment]
also tip, when adding shit to the game use a `Pull Request` not an `Issue`.

**Comment by Unkrown6YT** [comment]
Ok, I'm sorry
