### ISSUE TITLE
Bug Report: ui numbers

### ISSUE THREAD

**Issue by ghost** [Leather128/LeatherEngine#267]
**Hello, it's me you're looking for :)** 

There is a bug in game ui numbers.

When I hit a note it shows '0' when it is supposed to be '1'.

Here is a screenshot:
![well well well](https://user-images.githubusercontent.com/87716423/178399271-b936b22a-aa47-4d2e-8b05-6601b466a18c.png)

is easy to fix

**Comment by Leather128** [comment]
oh ye lemme just make the combo increase *before* displaying it, that would make sense lol

**Comment by Leather128** [comment]
fixed in [18b3ae6](https://github.com/Leather128/LeatherEngine/commit/18b3ae654248dff72edbf2463042b6e66adfbce8)[18b3ae6](https://github.com/Leather128/LeatherEngine/commit/18b3ae654248dff72edbf2463042b6e66adfbce8)
