### ISSUE TITLE
Value Exception

### ISSUE THREAD

**Issue by min89xd** [Leather128/LeatherEngine#27]
I get a value exception when I create a new stage

**Comment by Leather128** [comment]
can you provide more information?

**Comment by Leather128** [comment]
like what version of the game your running, (maybe stage .json?), are you running x64 or x32, etc.

**Comment by min89xd** [comment]
do you have discord?

**Comment by min89xd** [comment]
> like what version of the game your running, (maybe stage .json?), are you running x64 or x32, etc.

0.3.6, I am doing this with source code , 64 bits, i added first shaggy stage

**Comment by Leather128** [comment]
> 
> 
> do you have discord?

yes i do

**Comment by Leather128** [comment]
> 
> 
> > like what version of the game your running, (maybe stage .json?), are you running x64 or x32, etc.
> 
> 0.3.6, I am doing this with source code , 64 bits, i added first shaggy stage

you added everything correctly in right? (the stage images in stages/images/[stage name here/)

and added the stage to stageList.txt? and other stuffs? (also i already ported entire shaggy mod lol, so if you need stuff from it i can give) i do want to still fix this issue however.

**Comment by min89xd** [comment]
> > do you have discord?
> 
> yes i do


Could you tell me your discord username?

**Comment by Leather128** [comment]
Leather128#3538

**Comment by Leather128** [comment]
btw it was polymod problem
