### ISSUE TITLE
Question: Modcharting System + stuff about it

### ISSUE THREAD

**Issue by sanamasako** [Leather128/LeatherEngine#276]
Hey Leather, sorry if I'm flooding the place with questions. This time I have actual questions, and I won't be able to answer them by myself.

**The Modcharting System (as of now)**
So, as far as I know, LE uses Kade's modcharting system which is unfortunately very limited. Will LE ever have Psych's modcharting system? I know mods have already been made with Kade's, and if, say people tried to port the Kade-based mods to "0.4.3", they would break, so if you ever do add Psych's modcharting system... how are you going to do it other than making it available _alongside_ Kade's? Dumb idea, but maybe you could organize the two modcharting systems into their own folders to read from in the source, and for a modchart to read from either system, the user would have to put -kade or -psych at the end of the name? That's probably very stupid but the only way I see Kade and Psych modchart systems working together in LE unless you somehow make them interchangeable without errors (or you straight up combine them both which idfk you're going to do that).

**Stuff About The Modcharting System**
So, it's possible to load different songs through their charts. No modchart needed. It's possible to play different cutscenes based on variables that change. That needs a modchart. But, is it possible to switch difficulties as a whole, or load a different "next song" based on, let's say accuracy or misses? Similar to the whole "endcutscene" thing but with songs and difficulties. I would assume it's difficult since modcharts only apply to the song that's playing. I tried to load a different song under a script that would trigger if the song ends with an accuracy lower than 60 (setProperty("SONG", "song", "deez_nuts")), but of course, the song didn't load. Probably because I did it wrong and I don't know lua at all, or because it's just not possible. But, I still want to know. I'm gonna end this issue here before I end up writing an essay or getting redundant. If I wanted to switch which song plays next, or which difficulty to load, or maybe even both, what would that look like if it's even possible?

**Comment by Leather128** [comment]
1. I am not adding the Psych Engine Modcharts because they are a pain in the ass in source and very messy. (and the kade stuff isn't really that limited in the first place, you just gotta know all the functions mate)
2. No you can't load different difficulties yet because I never thought of that. (Also the reason `setProperty("SONG", "song", "deez_nuts")` doesn't work is because you're just setting the current song's name to that, not anything else)
