### ISSUE TITLE
Any idea why custom arrows don't line up with the notes?

### ISSUE THREAD

**Issue by BR14Nmusic** [Leather128/LeatherEngine#277]
Trying to make a ui skin but the arrows don't line up. Is there any way to offset only the judgement arrows or the note arrows without hard coding it into the code? All the assets should be centred and the only offsets I could find change arrow positions in the editor.

![image](https://user-images.githubusercontent.com/84362309/180935592-2db5282d-6359-4a96-bdef-80b63fc490f5.png)

**Comment by Leather128** [comment]
it seems you do not understand, your strum sprites (or note sprites) are just not centered. like seriously they just aren't. unless you can like send the xml or something to prove they are then uhhhh pretty sure they ain't centered buddy

**Comment by BR14Nmusic** [comment]
![default](https://user-images.githubusercontent.com/84362309/181131296-0a782b05-590d-46c9-9521-9c71ee889904.png)
![image](https://user-images.githubusercontent.com/84362309/181131359-61ec48c3-d363-4ed8-88b0-8e93c59dcb87.png)
I'm prettu sure this should be centred? looking at the x y width and height in it should match up. Also, different note sprite types line up with them so I'm really not sure what's wrong since it's only the static arrows that are having issues.
![image](https://user-images.githubusercontent.com/84362309/181131994-d16857bc-8ed6-4d05-aaf9-098f74d83f61.png)

**Comment by Leather128** [comment]
wait how is there 0 frameX, frameY, frameWidth, or frameHeight values for the strum xml data? there should be?

**Comment by Leather128** [comment]
question: did you use different pngs for all the animations? (if so, **did you actually center them properly in adobe animate??**)

**Comment by BR14Nmusic** [comment]
I used separate pngs for the animations and they're all aligned like this in adobe animate
![image](https://user-images.githubusercontent.com/84362309/181379417-6cf289d0-5067-453f-9784-97cd104a9c38.png)
![image](https://user-images.githubusercontent.com/84362309/181379852-a64e19e9-ec86-4ff6-b9b6-e0fa0ad3b294.png)
^the confirm arrows have two different frames
![image](https://user-images.githubusercontent.com/84362309/181379696-16d17741-0a33-4614-b37c-00abb4633850.png)

**Comment by Leather128** [comment]
are you sure all the pngs are aligned with each other?

**Comment by BR14Nmusic** [comment]
I'm pretty sure

**Comment by BR14Nmusic** [comment]
Okay, I think i've figured out the reason. I messed around with the size of the notes so i made a sprite sheet with dimensions closer to the default ui skin's default arrow set and then made it smaller. If the dimensions of a sprite was smaller than its default ui skin equivalent it was offset to the left, and if it was bigger (like my original arrows) they were offset to the right.

![image](https://user-images.githubusercontent.com/84362309/183270500-9c475b14-6ab1-461b-8ce9-88646c18afad.png)
bigger = offset to the right

![image](https://user-images.githubusercontent.com/84362309/183270505-a478eb42-b9c2-4256-a1c3-70e2cc3bb733.png)
this was very close to the original default ui skin's arrow dimensions but slightly bigger and it was offset less to the right

![image](https://user-images.githubusercontent.com/84362309/183270514-67ab9544-4c88-4555-b714-19788b55e6a5.png)
these were very tiney and they're offset to the left

So now I'm probably going to have to either make my ui skin's default arrows dimensions match the default ui skin. Which wouldn't be ideal since it would be better to have more freedom in the dimensions of custom notes in different ui skins. Hopefully this made sense

**Comment by Leather128** [comment]
i guess that makes sense, tbh i'm just confused why it's happening though as it should scale fine to any size (like for example, how pixel notes are just tiny sprites scaled up by 6 without meeting the exact same dimensions as normal notes)
