### ISSUE TITLE
Bug Report: source/debuggers/ChartingState.hx:10: characters 8-36 : Type not found : polymod.fs.PolymodFileSystem

### ISSUE THREAD

**Issue by ryi3r** [Leather128/LeatherEngine#29]
source/debuggers/ChartingState.hx:10: characters 8-36 : Type not found : polymod.fs.PolymodFileSystem
Just downloaded the version 0.3.6 of this engine and i can't compile at first try.

**Comment by Leather128** [comment]
do you have polymod (and the most recent version of it) installed?

**Comment by ryi3r** [comment]
Yes.

**Comment by Leather128** [comment]
What platform are you building to? (html5, windows, etc).

**Comment by ryi3r** [comment]
Windows.

**Comment by Leather128** [comment]
And you're completely 100% sure you have the most recent, correct version, of polymod installed? (https://github.com/larsiusprime/polymod)

**Comment by ryi3r** [comment]
Yeah, it's the same link i put while installing it.

**Comment by ryi3r** [comment]
Plus if i put as comment that line of code, the whole engine works perfectly.

**Comment by Leather128** [comment]
Weird, guess I'l comment it out for now and hope nothing is broken?
