### ISSUE TITLE
Question: Loading Screens

### ISSUE THREAD

**Issue by RhysRJJ** [Leather128/LeatherEngine#290]
Is it possible to add loading screens to leather with the source code? (If possible I'd like to know what code I need for it)

Also I'm not sure if the current source code is meant to compile into 0.4.1 instead of the newest version

**Comment by Leather128** [comment]
it is possible obviously, and the current source code shouldn't be compiling into 0.4.1 (unless you're using 0.4.2 release source because i think i might've changed the version on github for that AFTER it was released)

**Comment by RhysRJJ** [comment]
That would explain my issue, how would I go about getting the 0.4.2 source then?

**Comment by Leather128** [comment]
well it probably *Is* 0.4.2 source, but if you really want the version stuff you could just look at the commit history and find where i changed the version (859ec4f2b5e67cc0c48c732b7f58b54da429fdad i think).

**Comment by RhysRJJ** [comment]
I looked through the commits and found the version I was looking for (I like using the chart editor zoom), thanks for the help
