### ISSUE TITLE
Play characters animation on a character group

### ISSUE THREAD

**Issue by RhysRJJ** [Leather128/LeatherEngine#291]
Is it possible to make one character in a character group (Like matt) play an animation

In the stuff it's set on "dad1" which I believe should make the animation play on that character but it doesn't seem to work so I'm unsure as to if I need to do smth else for it to work or if it just isn't possible

**Comment by Leather128** [comment]
The way you access group characters is like this:

`character's original name` + `Character` + `number from 0 to the amount of characters minus 1 for the character`

ex (shaggy and matt group character):

`dadCharacter0` -> red shaggy
`dadCharacter1` -> matt

(works with dad, bf, and gf btw)
