### ISSUE TITLE
Enhancement: Add a Lua callback to check if a Lua Sprite exists 

### ISSUE THREAD

**Issue by DetectiveBaldi** [Leather128/LeatherEngine#297]
Just a way to check if a Lua sprite exists. Would be useful in certain scenarios I think.

**Comment by Leather128** [comment]
get('luaSpriteOrWhatever.exists') would probably work anyways but ok i'll do it rq

**Comment by Leather128** [comment]
82920bc05620a3d30b223bbb10e2e2690115af82
