### ISSUE TITLE
Question: is there a 0.5 leather engine in existence yet

### ISSUE THREAD

**Issue by fnfporterhi** [Leather128/LeatherEngine#306]
## What is your question?
i saw a youtube video using 0.5 leather engine, curious if a build existed at all

**Comment by JordanSantiagoYT** [comment]
if it's that fd but gf helps you v6 video, it's an action build

**Comment by fnfporterhi** [comment]
oh bro i saw it and i was like "wait fr leather engine but 0.5 real"

**Comment by fnfporterhi** [comment]
whats an action build :skull:

**Comment by Leather128** [comment]
> #### Please check for duplicates or similar issues before asking your question.
> ## What is your question?
> 
> i saw a youtube video using 0.5 leather engine, curious if a build existed at all

if the video was a bit older then it was probably actually a dev build of 0.4.2, and if it was more recent it was probably a dev build of 0.5.0 (yes i'm working on it slowly lol!!!)

**Comment by fnfporterhi** [comment]
> > #### Please check for duplicates or similar issues before asking your question.
> > ## What is your question?
> > i saw a youtube video using 0.5 leather engine, curious if a build existed at all
> 
> if the video was a bit older then it was probably actually a dev build of 0.4.2, and if it was more recent it was probably a dev build of 0.5.0 (yes i'm working on it slowly lol!!!)

yeah his video was very recent, a couple of days ago (lmao youre fine bro i ported all your mods into one engine so im surviving! thanks for the great engine)
