### ISSUE TITLE
Bug Report: Charting glitch

### ISSUE THREAD

**Issue by ryi3r** [Leather128/LeatherEngine#31]
While i was charting, going after the 10 section, the screen goes black, my setup was 12k, 180 bpm, 3 arrow speed, when it goes black it stays like that, until you get out of the editor.
![image](https://user-images.githubusercontent.com/50798713/141020687-12a300f2-1fdc-42d8-866d-ef36f1ec1d73.png)
I was on all of the sections pointing to P1 and the song name is "secret".

**Comment by Leather128** [comment]
weird, do you have any idea what maybe be the cause of this? (also did you use change bpm at any point in the song?)

**Comment by Leather128** [comment]
personally for me, there isn't any obvious reason why this happens (i've experienced this too) but I never could figure out what caused it (because the current charter is pretty buggy and confusing).

**Comment by ryi3r** [comment]
> 
> 
> weird, do you have any idea what maybe be the cause of this? (also did you use change bpm at any point in the song?)

Maybe cause i didnt set new bpm.

**Comment by Leather128** [comment]
That can happen, but it shouldn't make anything happen (because it's supposed to add it when over 0 bpm but maybe I should make sure)

**Comment by ryi3r** [comment]
Lemme try it out.

**Comment by ryi3r** [comment]
Nvm, it broke even more.

**Comment by ryi3r** [comment]
Nevermind, i might have found the reason why it happens.
![image](https://user-images.githubusercontent.com/50798713/141036648-335397f9-8901-4163-af48-03d03e6b5281.png)
![image](https://user-images.githubusercontent.com/50798713/141036660-670d11c6-6204-4094-9084-561852ad79c0.png)
I think you can limit those variables so they don't pop-off in negative numbers.

**Comment by ryi3r** [comment]
Above 10 seems to give back this number.

**Comment by ryi3r** [comment]
When you play the song it gets stuck by here
![image](https://user-images.githubusercontent.com/50798713/141037008-46115461-9e51-4ee1-8c0e-3fb2e9e7b94f.png)

**Comment by ryi3r** [comment]
![image](https://user-images.githubusercontent.com/50798713/141037754-69679d7d-a9e6-4cef-b23e-06695e5b527d.png)
touching the code ( ![image](https://user-images.githubusercontent.com/50798713/141037781-2cd8dd10-bc70-4cc4-99ea-fc1acdbd8a18.png) ) it seems like the strumLine goes to space, literally

**Comment by ryi3r** [comment]
Just noticed this:
![image](https://user-images.githubusercontent.com/50798713/141038531-f76455f1-d147-4e95-a250-6ff7d169ced6.png)
and if i move with mouse wheel:
![image](https://user-images.githubusercontent.com/50798713/141038569-4f1cab69-7262-46e7-bd3e-ed5640c09590.png)
(This is off-topic but can you fix the mouse in the editor? it's really bugging me when it doesn't appear.)
EDIT: Something related to the BPM or the song might be the problem.

**Comment by Leather128** [comment]
Seems like the bpm just flat out broke (aka it's 0) explaining the negative (and positive) infinity values.

**Comment by Leather128** [comment]
Seems weird that the song time is `inf` but I have a feeling this is due to the BPM being 0.

**Comment by Leather128** [comment]
This *(should)* be fixed in commit [b3903ac](https://github.com/Leather128/LeatherEngine/commit/b3903ac3f67327b09ea7c46706c80b6a573caa96), if it's not actually fixed (it fixed it for me, maybe something is still wrong for you on the latest commits somehow?) then just reopen this issue. For now it will be closed as the issue has (hopefully) been fully solved.
