### ISSUE TITLE
Enhancement: Linux FIle

### ISSUE THREAD

**Issue by ghost** [Leather128/LeatherEngine#312]
Uh, so
i do not like this
![image](https://user-images.githubusercontent.com/99573698/219967109-15bc866d-5ef2-4c42-b0f0-d576c2a97e24.png)

so i did this
![image](https://user-images.githubusercontent.com/99573698/219967140-1431e12c-73c3-4e11-8e0c-3359adb3998a.png)

```xml
<!-- Linux thing-->
<window if="linux" file="LeatherEngine"/>
```

**Comment by Leather128** [comment]
haha i dont wanna reset everyone's save data
