### ISSUE TITLE
Bug Report: My game crashes when loading anything else other than mods

### ISSUE THREAD

**Issue by TristanTheCoderModder** [Leather128/LeatherEngine#32]
I'm on Version 0.3.6 and when i load freeplay, story mode, or options it acts like its loading then crashes, please help

**Comment by ryi3r** [comment]
Does it show any error?

**Comment by Leather128** [comment]
does this happen on any other version of fnf?

are you using 64 bit or 32 bit, and are you building from source or not?

**Comment by TristanTheCoderModder** [comment]
it doesnt happen to any other version

i'm using 64 bit, and i cant use source for some reason.
and also no error

**Comment by Leather128** [comment]
Question: How much RAM / Memory do you have?

**Comment by TristanTheCoderModder** [comment]
Well, now i have a different problem since i fixed the crashing- its the offsets with multiple characters now (like 2 characters in one config-)
