### ISSUE TITLE
Enhancement: (Option to) decrease gap between arrows?

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#34]
I couldn't help but notice that the gap between arrows is quite noticeable with more than 4 keys. This is a gap that is remedied in, say, the Shaggy mod, by squishing them together a bit.

Considering this engine supports up to 18 keys, it might be best to do the same, that way the arrows aren't so small and hard to hit. If you squish them together a bit like the Shaggy mod does in 9 key, you can expand the arrows' size and make them easier to see.

**Comment by Leather128** [comment]
This seems like a good idea, it may require some reworking on how arrow placement and sizing is handled however, I will consider this since I feel as if a lot of people will want this (especially after getting used to 9, 6, or 7 key in the shaggy mod)

**Comment by Onemario1234** [comment]
Yeah, I got really used to the Shaggy mod's arrow placement. Moving to Leather Engine was kinda jarring at first.

**Comment by Onemario1234** [comment]
Not to mention being able to see all the arrows in songs using larger key counts would be nice. Lol

**Comment by Leather128** [comment]
Fixed in commit [#e4e2cd2](https://github.com/Leather128/LeatherEngine/commit/e4e2cd27e31d7e6521ca40f1ac2175dbc810a475).
