### ISSUE TITLE
Bug Report: Both health icons display as BF on Chart screen

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#35]
![image](https://user-images.githubusercontent.com/25996506/141259576-29ec5a78-8d32-48a7-8471-3c8191bf273e.png)
It seems to happen every time, and the opponent isn't BF in-game. It's only the icons, only for the chart screen.

**Comment by Leather128** [comment]
This is because, your opponent character is `mom-car` aka a character who reuses a health icon (and also doesn't have a .json for their character) meaning that they are hardcoded in the game. I'll fix this soon by just making each character have their own .json file.

**Comment by Onemario1234** [comment]
Ohh, that makes sense.
