### ISSUE TITLE
Question: How do I scroll sideways for 13+ Key Charts?

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#36]
![image](https://user-images.githubusercontent.com/25996506/141260255-16477639-a88c-4a82-922a-8f85c59e83d8.png)
Using any Key count above 12 makes it impossible to add notes to the opponent's side. Is there a way to scroll sideways that I don't know about, or has that not been properly implemented yet?

**Comment by theloser7455** [comment]
i think leather will fix the 13 or more keys opponent's side size on chart or something

**Comment by Leather128** [comment]
yeah this is something i've been planning on adding but haven't added yet, guess i'll do it now since leather engine is getting more popular

**Comment by flowerbearttv** [comment]
Temp solution is too swap section notes to put notes on that side

**Comment by Leather128** [comment]
Added in commit [#0725ad9](https://github.com/Leather128/LeatherEngine/commit/0725ad96624a4b4e5d728b1fef0ca864f4759eb3). (Use Control + Mouse Wheel)
