### ISSUE TITLE
Question: Regarding removal of stolen assets

### ISSUE THREAD

**Issue by daisukidaisy** [Leather128/LeatherEngine#43]
There is a second arrow shape (present with 10 or more keys) that looks familiar. This isn't from [Vice's Shaggy 21k mod](https://www.youtube.com/post/UgwJNgWPKehIX1-fY7J4AaABCQ), is it?
Vice doesn't want anyone using the 21k assets. The original 21k mod is privated for that reason.

**Comment by Leather128** [comment]
They aren't, but the reference @Ronezkj15 used was probably that mod, or something similar (for the pixel versions that I later adapted to the normal arrows with Adobe Animate).
