### ISSUE TITLE
Enhancement: Option for Black Backdrop on Player's Side

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#44]
Songs with more than 9 keys and a fast scroll speed can make it really tough to read incoming notes, especially if it's against a moving background or something similar. The option to add a transparent, black backdrop for your side of the chart while playing would make it much easier to see incoming notes in songs with a higher key count.

**Comment by Leather128** [comment]
Seems like a good idea, will probably add this soon.

**Comment by Leather128** [comment]
Added in commit [40e1a8f](https://github.com/Leather128/LeatherEngine/commit/40e1a8f16b243df38808fa806a625bbd3df092b8).
