### ISSUE TITLE
Enhancement: Option for Camellia's Marvelous judgements

### ISSUE THREAD

**Issue by daisukidaisy** [Leather128/LeatherEngine#45]
I'm not sure what the default timing window is from the Camellia mod itself, but I presume it's 22.5 ms, half of the Sick window.
A Marvelous is 400 points in Vs Camellia, and an "Epic" (same thing?) is 550 points in Times & Tribulations.
This could be turned off either by an on/off option in the Gameplay section of Settings or by simply setting the timing window to 0 ms (default) after selecting Judgement Timings.
The Marvelous rating image could just be the rainbow "Sick!!" from old versions of Kade Engine, shown below. This would be a nice reference to osu!mania's rainbow 300s.

![sick](https://user-images.githubusercontent.com/91840623/141655024-c6a08fa6-e076-4c81-9281-6003bece16b8.png)

**Comment by Leather128** [comment]
Added in [#b4a9197](https://github.com/Leather128/LeatherEngine/commit/b4a919701479aa5b37ebe55fa85ef949b3b6d49c).
