### ISSUE TITLE
Bug Report: Hold Caution and Death Notes don't work

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#46]
![image](https://user-images.githubusercontent.com/25996506/141672048-fe751d22-4106-46d4-ac02-f387ebe98a8b.png)
You probably know about this one already, but I'm posting it just to be safe.

Alongside the graphics being bugged, they also stop working right. Caution Notes can be released mid-hold without insta-killing, and Death Notes can be hit safely without fear of death.

**Comment by Leather128** [comment]
Yeah it's a thing I just haven't fixed yet since I haven't added the held variants of those arrows yet (possibly will in future however)

**Comment by Leather128** [comment]
oh yeah btw i fixed this
