### ISSUE TITLE
Enhancement: Unhardcode mania arangements + infinite mania

### ISSUE THREAD

**Issue by flowerbearttv** [Leather128/LeatherEngine#48]
Make it so there is a text file with the mania arrow arrangements, like 9k being
`LEFT DOWN UP RIGHT DIAMOND LEFT DOWN UP RIGHT`
or 10k being
`LEFT DOWN UP RIGHT UP2 DOWN2 LEFT DOWN UP RIGHT`.
or if the modder wanted to add more mania, like 21 keys, they could specify the mania arrangement as well as the keybinds in the songs data folder.
This suggestion is bloated with lots of logistical problems, but i think unhardcoding one of the main features of the engine would be fun

**Comment by Leather128** [comment]
that seems like a good idea actually, shouldn't be too hard since the arrow values are already in an array.

**Comment by Leather128** [comment]
actually that makes this a lot easier to implement than i thought lol

**Comment by Onemario1234** [comment]
This sounds like it would be such a cool feature if added.

**Comment by Leather128** [comment]
Added in commit [#59488e6](https://github.com/Leather128/LeatherEngine/commit/59488e647fe8e1697fee8bc825e88894620406e2)!!!
