### ISSUE TITLE
Enhancement: Arrow "Types"

### ISSUE THREAD

**Issue by Leather128** [Leather128/LeatherEngine#5]
## What is your suggestion, and why should it be implemented?

(I got this idea from @Ronezkj15 originally btw lol)

Basically you can set an arrow type for different arrows (and a general arrow type for songs too).
That would have different stats (like hit health, miss damage, etc).

And that are fully customizeable by text files in 'preload/data/arrow_data/'

Here's what I made as a concept (in a discord message lol):

```
        (in preload images ui/arrows/)                                       (optional)
ArrowTemplate:SkinFileName:On-Hit-Health:On-Miss-Health:Hit-Sound:Makes-Miss:Hit-Effect
```

so example:

```
FireArrow:fire_arrows_assets:-0.15:0:Fire-Sound:true:fire_arrow_effect
```

Adding this to the game would add more customization, and be kind of an extension of #4.

**Comment by Ronezkj15** [comment]
fun fact: this was literally the first thing I suggested for leather engine lol

**Comment by Leather128** [comment]
tru

**Comment by Leather128** [comment]
FINALLY DONE
