### ISSUE TITLE
Question: Custom Note Types (like in Psych Engine)

### ISSUE THREAD

**Issue by MasterDirector99** [Leather128/LeatherEngine#54]
@Leather128 I have a question, Could you make the Custom Note Types unlike Psych Engine?

**Comment by Leather128** [comment]
you already can ([link](https://github.com/Leather128/LeatherEngine/wiki/Creating-an-Arrow-Type)) but it doesn't currently use lua (aka a lot less customizeable unless you make a modchart for it in song). in future will prolly make it able to be customized more tho

**Comment by MasterDirector99** [comment]
Oh, right. Thanks btw
