### ISSUE TITLE
Question: Discord Server

### ISSUE THREAD

**Issue by MasterDirector99** [Leather128/LeatherEngine#57]
## What is your question?
Do you have a discord account & server? Because I wanted to drop some ideas for the future Leather Engine updates.

**Comment by Leather128** [comment]
i have a discord account, but no server for leather engine. and you can just post ideas to this page (issues) or the discussions if you want

**Comment by MasterDirector99** [comment]
Oh good, Discord Tag?

**Comment by Leather128** [comment]
Leather128#3538

**Comment by Leather128** [comment]
i would send it, but the problem is that i have my "who can add you as a friend" set to server members, and i don't really want to change it. so maybe i could just make a leather engine server in future or something ¯\_(ツ)_/¯

**Comment by MasterDirector99** [comment]
I have my tag: Alex Director#7124

**Comment by Leather128** [comment]
alright
