### ISSUE TITLE
Question: What is the "All Shag Final" option under the Compatibility tab?

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#59]
![image](https://user-images.githubusercontent.com/25996506/143089588-c1a15b24-ed52-4c16-bb3a-893e337006a5.png)
It doesn't _seem_ to do anything when clicked.

**Comment by Leather128** [comment]
basically if you have a chart from final destination god mode (or expurgation) it will convert all those notes into the correct arrow types (that are used in leather engine).
