### ISSUE TITLE
Enhancements: More competitive-oriented features (very, very long post)

### ISSUE THREAD

**Issue by daisukidaisy** [Leather128/LeatherEngine#62]
### first off
if people dont want to see all these kade engine looking info you should make a new section of the options menu to disable showing some of the things im about to mention
### important
I don't expect everything in this to be implemented in the very next update. Please take as much time as you need! As someone with minimal experience in coding, I'm sure full-scale modded engine development is very, very difficult.
### ok actual features
**more stats**
- MFC = Full combo with all Marvelous judgements (with Marvelous judgements turned on in settings) (this is already there but defined differently)
- PFC(/SFC) = Full combo with no Good or Bad judgements (perfect score with Marvelous turned off)
- SDP(/SDS) (Single Digit Perfects/Sicks) = PFC with less than 10 Sick judgements (with Marvelous judgements turned on)
- GFC = Full combo with no Bad judgements
- SDG (Single Digit Goods) = GFC with less than 10 Good judgements
- FC = No combo breaks (this is already there)
- SDB (Single Digit Bads) = FC with less than 10 Bad judgements
- SDCB (Single Digit Combo Breaks) = Less than 10 combo breaks (this is already there)
- Clear = None of the above (this is already there)

**Attack ratios**
In StepMania/Etterna, MA (Marvelous Attack) is your ratio of Marvelous judgements to other judgements, and PA (Perfect Attack) is your ratio of either Marvelous or Perfect (Sick) judgements to lower judgements. This could be shown in a results screen at the end, or in real time during gameplay on the side of the screen.

**Judgement counts**
Instead of just showing combo breaks, you could put this on the side of the screen:
- "Marvelous: (A)"
- "Sick: (B)"
- "Good: (C)"
- "Bad: (D)"
- "Combo Break: (E)"
Where each letter represents how many of each respective judgement (or how many combo breaks) you have. This could also just be shown in a results screen.

**Results screen as mentioned earlier**
This could show all of what I mentioned above, as well as a hit graph: ![a hit graph](https://user-images.githubusercontent.com/91840623/143267692-e4b9b150-8fb3-4547-86ec-9b86c40dac7c.png), max combo, and stuff from your settings (judgement timings, offset, ghost tapping toggle, etc.)

**Replay files**
Basically, a file that plays the chart using your recorded inputs. This could be used in any number of ways; recording runs after they already happened, sharing replays directly with others, anti-cheat, etc. This may cause users' PCs to use more resources during runs, but for anyone wishing to maintain a leaderboard or just attempt to back up claims of insane plays, this is a must have. This may be the hardest feature to implement out of anything I listed, so no pressure.

### but why tho?
Yes, most of these ideas come from either Kade Engine or more serious rhythm games. No other engine seems to provide a good enough alternative with all of its competitive features, but unfortunately, Kade Engine is extremely broken. Since Leather Engine aims to have as much customization as possible, I see hope in this project as one to take its place, and actually work as intended.

**Comment by Leather128** [comment]
aight, will be adding this

**Comment by Leather128** [comment]
update: rn we have `more stats`, `judgement counts`, `replay files`, and `attack ratios` (basically i just need to add the results screen)

**Comment by Leather128** [comment]
All added in commit [#228c6b4](https://github.com/Leather128/LeatherEngine/commit/228c6b42eacc6ffa25fef199b8fa9f2b4ef8bcb1)!!!
