### ISSUE TITLE
Question: Why is it telling me that 303.txt cant be found inside of ui skins?

### ISSUE THREAD

**Issue by sussyimpoopstor** [Leather128/LeatherEngine#64]
I didnt add any new ui I just tried to play my vs arch port and that happened. do I just make a 303.txt or do something different. Is it a missing file or a bug.

**Comment by Leather128** [comment]
prolly cuz the chart your using uses pysch engine, and has something in the chart that leather engine cant understand

**Comment by Leather128** [comment]
basically i thinks something (probably an event or something) is an arrow type
