### ISSUE TITLE
Enhancement: Rearrange the new arrows in 16k to match 18k?

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#67]
![image](https://user-images.githubusercontent.com/25996506/143724600-0ed22233-0705-49f2-b343-24cf50dafa63.png)
![image](https://user-images.githubusercontent.com/25996506/143724607-b418f962-ff7f-4e13-afb5-a0ee7a20b955.png)
The new, sharper arrows used in 16k are in a different formation than 18k, which might be a bit confusing to most. (Especially with the order of arrow directions being different than the usual "left down up right.") I think it'd be a good idea to use the same general formation as 18k, just without the diamond and cross.

**Comment by Leather128** [comment]
yea prolly, i mean @Ronezkj15 was the one who made the og designs and layouts, but i think i could fix this

**Comment by flowerbearttv** [comment]
> yea prolly, i mean @Ronezkj15 was the one who made the og designs and layouts, but i think i could fix this

yeah this kinda also works with my custom mania layouts enhancement i mentioned earlier. where if that were implemented, that could be changed in a new update or something

**Comment by Leather128** [comment]
yea

**Comment by Leather128** [comment]
Fixed in commit [68c50ed](https://github.com/Leather128/LeatherEngine/commit/68c50edf316df7df30344704f3da03e0f910f64f).
