### ISSUE TITLE
Question: Video End Cutscene

### ISSUE THREAD

**Issue by MasterDirector99** [Leather128/LeatherEngine#68]
Do you think you'll add the post-song video cutscene?

**Comment by Leather128** [comment]
ok i'll make cutscenes playable at end of song (not rn but soon since it should be easy to make)

**Comment by Leather128** [comment]
Added in commit [#2906f30](https://github.com/Leather128/LeatherEngine/commit/2906f30f20ffb24271e54ccf767ed971305bf92d).
