### ISSUE TITLE
Enhancement: Decrease Gap Between Arrows (cont.)

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#69]
I already made a post talking about how it would benefit the mod if 5+ key modes squished the keys together a bit to fit them on-screen better and make them look slicker. I decided to make a post comparing how 9 keys look between vs. Shaggy and Leather Engine, to better showcase my point.

vs. Shaggy
![image](https://user-images.githubusercontent.com/25996506/143828913-fb35b6f3-64c2-4939-9977-fcba1871bb27.png)
Leather Engine
![image](https://user-images.githubusercontent.com/25996506/143829226-3ba205a8-d11e-4cca-8d5d-e9ff07727635.png)

Because Leather Engine keeps the same 4 key gap, the arrows had to be shrunken in size to fit the screen, and as a result, they're ever so slightly harder to see, and it would take some adjusting to, no doubt, as well.

**Comment by Leather128** [comment]
I will definitely be implementing this, I'm just not too sure how to go about it yet. I'm sure I can find a way however.

**Comment by Onemario1234** [comment]
Well, what's the current roadblock?

**Comment by Leather128** [comment]
Probably just making it all customizable, while not breaking any other systems in the process

**Comment by Leather128** [comment]
Fixed in commit [#e4e2cd2](https://github.com/Leather128/LeatherEngine/commit/e4e2cd27e31d7e6521ca40f1ac2175dbc810a475).
