### ISSUE TITLE
Bug(?) Report: Dropped sustains are not fully punished

### ISSUE THREAD

**Issue by daisukidaisy** [Leather128/LeatherEngine#70]
If you drop a sustain (as of most recent release), the game will subtract 10 points per 16th(?) as it should, but it will not count as a combo break nor will it drop your accuracy. Generally, dropping a sustain should be punishable, as this is not Clone Hero.

**Comment by Onemario1234** [comment]
Accuracy I think it should lower, but I don't think it should increase the number of misses. I feel it makes sense if missing any point of a sustain note would count as only one miss.

**Comment by Leather128** [comment]
Dropped sustains are not fully punished as of now, because I am planning a rework that combines all the parts of a sustain note into one (because right now they are seperate sections) and having each section give a miss would be unfair. This will be fixed when I rework them.

**Comment by Leather128** [comment]
I must add however, they are still supposed to drop your accuracy.

**Comment by Leather128** [comment]
Checked on the most recent commits, sustain notes lower accuracy. So I guess part of this issue is out of date.

**Comment by Leather128** [comment]
Fixed in [#5683375](5683375141837d30971f7e76ec85cc83931625f1). Also added an option to turn off gaining misses from held notes because why not. Also also, I made you get a miss only once from missing a sustain note (because before it would give a miss for each sustain note section).
