### ISSUE TITLE
Death animation on the same character

### ISSUE THREAD

**Issue by dimuzicle** [Leather128/LeatherEngine#72]
## What is your question?
can ya do that for now?
and how?

**Comment by Leather128** [comment]
wdym death animation on the same character?

**Comment by dimuzicle** [comment]
without bf-dead character

**Comment by Leather128** [comment]
uh set the "deathCharacter" property in the config.json of the character to the character you want to be used (it can be the same character that is being played as)

**Comment by dimuzicle** [comment]
I tried but it's the same animation as bf one
I use custom bf character that uses unique death animation

**Comment by Leather128** [comment]
can i see the character's config.json?

**Comment by dimuzicle** [comment]
{
    "defaultFlipX": true,
    "dancesLeftAndRight": false,
    "imagePath": "loly_bf_assets",
    "spritesheetType": "SPARROW",
    "barColor": [81, 201, 219],
	"deathCharacter": "bf-loly",
	"positionOffset": [0, 30],
    "offsetsFlipWhenEnemy": true,
    "offsetsFlipWhenPlayer": false,
    "animations": [
        {
            "name": "idle",
            "animation_name": "BF idle dance",
            "fps": 24,
            "looped": false
        },
        {
            "name": "singLEFT",
            "animation_name": "BF NOTE LEFT0",
            "fps": 24,
            "looped": false
        },
        {
            "name": "singDOWN",
            "animation_name": "BF NOTE DOWN0",
            "fps": 24,
            "looped": false
        },
        {
            "name": "singUP",
            "animation_name": "BF NOTE UP0",
            "fps": 24,
            "looped": false
        },
        {
            "name": "singRIGHT",
            "animation_name": "BF NOTE RIGHT0",
            "fps": 24,
            "looped": false
        },
        {
            "name": "singLEFTmiss",
            "animation_name": "BF NOTE LEFT MISS",
            "fps": 24,
            "looped": false
        },
        {
            "name": "singDOWNmiss",
            "animation_name": "BF NOTE DOWN MISS",
            "fps": 24,
            "looped": false
        },
        {
            "name": "singUPmiss",
            "animation_name": "BF NOTE UP MISS",
            "fps": 24,
            "looped": false
        },
        {
            "name": "singRIGHTmiss",
            "animation_name": "BF NOTE RIGHT MISS",
            "fps": 24,
            "looped": false
        },
        {
            "name": "hey",
            "animation_name": "BF HEY",
            "fps": 24,
            "looped": false
        },
        {
            "name": "scared",
            "animation_name": "BF idle shaking",
            "fps": 24,
            "looped": false
        },
		{
            "name": "firstDeath",
            "animation_name": "BF dies",
            "fps": 24,
            "looped": false
        },
        {
            "name": "deathLoop",
            "animation_name": "BF Dead Loop",
            "fps": 24,
            "looped": true
        },
		{
            "name": "deathConfirm",
            "animation_name": "BF Dead confirm",
            "fps": 24,
            "looped": false
        }
    ]
}

**Comment by dimuzicle** [comment]
it's rosie week 2 mod btw

**Comment by Leather128** [comment]
oops sorry

**Comment by Leather128** [comment]
i forgot that the property name isn't `deathCharacter` it's `deathCharacterName`
