### ISSUE TITLE
Bug Report: PA doesn't count Marvelous hits

### ISSUE THREAD

**Issue by daisukidaisy** [Leather128/LeatherEngine#73]
PA (Perfect Attack) should compare both Marvelous AND Perfect hits combined to lower timings. I thought I made that clear but I guess not.

**Comment by Leather128** [comment]
oh ok

**Comment by Leather128** [comment]
lemme fix that

**Comment by Leather128** [comment]
fixed in commit [#9b814c4](https://github.com/Leather128/LeatherEngine/commit/9b814c467bbf2f563bd6f616d71f9c1986f85635).
