### ISSUE TITLE
Enhancement: Add this pls

### ISSUE THREAD

**Issue by MadGuyXD** [Leather128/LeatherEngine#77]
can you add the event note look like in psych engine, pls

and fix the icon in charting

**Comment by Leather128** [comment]
wdym fix the icon in charting?

**Comment by MadGuyXD** [comment]
oh srry, im use the old version so...im still see 2 bf icon

**Comment by Leather128** [comment]
oh lol, that should be fixed

**Comment by Leather128** [comment]
also next time use the bug tag k?
