### ISSUE TITLE
Game crashes when loading mod songs

### ISSUE THREAD

**Issue by JordanSantiagoYT** [Leather128/LeatherEngine#83]
Decided to try the new update for leather engine. I added the shaggy mod port after downloading. Everything worked fine until I tried to load a modded song. The song would not load. Normal songs are the only ones that load.

Happens in Version 0.4.0.2

**Comment by Leather128** [comment]
are you running 64 bit or 32 bit?

**Comment by Leather128** [comment]
also which song?

**Comment by JordanSantiagoYT** [comment]
> are you running 64 bit or 32 bit?

64 bit

> also which song?

kaio ken

**Comment by JordanSantiagoYT** [comment]
update: figured it out. i did something and found something i did with the character data was what made the songs not load
