### ISSUE TITLE
Enhancement: Add health drain notes

### ISSUE THREAD

**Issue by ScratchRZL** [Leather128/LeatherEngine#84]
Add notes that drain health

**Comment by Leather128** [comment]
ok guess i'll make custom lua coded notes soon then (since that's what you'd need for that)

**Comment by Leather128** [comment]
question: you don't mean like the opponent hits a note and it lowers your health right?

**Comment by ScratchRZL** [comment]
yes

**Comment by ScratchRZL** [comment]
i do
but make it drain your health for a few seconds if you hit one on your side
