### ISSUE TITLE
Bug Report: 21+ keys don't display binds correctly.

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#85]
Here's 20 keys. Displays fine enough.
![image](https://user-images.githubusercontent.com/25996506/145903703-4f13acf6-135c-410b-9b17-cbf8c4515431.png)
21 keys. Now it's getting too small.
![image](https://user-images.githubusercontent.com/25996506/145903774-aa19d2a0-c344-4331-8ad5-f4a7ef358d23.png)
Way too small now at 22 keys.
![image](https://user-images.githubusercontent.com/25996506/145904000-9302b9fa-6791-4d50-a378-7bd2f4a403b2.png)
23 keys is illegible.
![image](https://user-images.githubusercontent.com/25996506/145904065-5327071f-ecbc-4daf-beb2-1abfbc01a492.png)
24 keys and up just fails to display binds altogether because they're too small.
![image](https://user-images.githubusercontent.com/25996506/145904124-8a5a4f6f-0ad1-4481-b6d2-208572f9424d.png)
This also goes for in-game with the keybind reminders.

**Comment by Leather128** [comment]
ok i will fix dat, (it happens mainly cuz the size of the keys is hardcoded and doesn't just change with the size of the arrows, as it should)

**Comment by Onemario1234** [comment]
Had a feeling it was something along those lines.

**Comment by Leather128** [comment]
fixed in 818d34d

**Comment by Unkrown6YT** [comment]
How to get 19+ keys
