### ISSUE TITLE
Enhancement: Separate Enemy Note Splashes and Player Note Splashes?

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#86]
This suggestion is a small cosmetic thing. Change the current "Note Splashes" option into two separate options. One for the enemy notes and one for the player notes.

Alternatively, a Note Splash option that toggles between three settings. No Splash, Player Only, and "Player & Enemy"

**Comment by Leather128** [comment]
sounds cool

**Comment by Leather128** [comment]
Added in commit 56c1f399ace7afa49122b1ed8363d41fd962d266
