### ISSUE TITLE
Question: How do i create more than 18 keys

### ISSUE THREAD

**Issue by flowerbearttv** [Leather128/LeatherEngine#88]
Whenever i try to create more than 18 keys the game doesn't show the keys in the bind menu or the game, and when I append data to them using a mod it doesn't work. What am I doing wrong?

**Comment by Leather128** [comment]
wait so you are modifying the key sets with a mod right?

**Comment by flowerbearttv** [comment]
> wait so you are modifying the key sets with a mod right?

i was originally modifying them directly in the game and the notes were not appearing, in game. worked fine in the chart editor though. used _append in a mod next and it did not work

**Comment by Leather128** [comment]
oh, yeah there is a bug rn where you can't use mods to add extra keys (or even modify the normal ones) so sorry about that

**Comment by Leather128** [comment]
btw that bug has been fixed now but yea
