### ISSUE TITLE
Enhancement: Lua scriptable notes

### ISSUE THREAD

**Issue by flowerbearttv** [Leather128/LeatherEngine#90]
So I saw another enhancement to add health drain notes. But I feel as if that can be expanded. How about when you miss or hit a note it calls a Lua function with the type of the note being passed through as a string. For example, you could create notes that do nothing but set up a mod chart that recreates black sun's mechanic or something.

**Comment by Leather128** [comment]
it already does have that tho

**Comment by Leather128** [comment]
which are:

```lua
function playerOneSing(noteDirection, songPosition, arrowType)
      -- code goes here
end

function playerOneSingHeld(noteDirection, songPosition, arrowType)
      -- code goes here
end

function playerOneMiss(noteDirection, songPosition, arrow_Type)
      -- code goes here
end

function playerTwoSing(noteDirection, songPosition, arrowType)
      -- code goes here
end

function playerTwoSingHeld(noteDirection, songPosition, arrowType)
      -- code goes here
end
```

(keep in mind for playerTwoSing and playerTwoSingHeld you have to have commit 33529f2 (most recent as of posting this) or later for the arrow type to work in the player two functions)

also remember that noteDirection is the number (note data) of the note, aka (for 4k) left = 0, down = 1, up = 2, etc.

**Comment by Leather128** [comment]
although in future, i will have notes that can be entirely coded in .lua (like in psych engine) but as of now that's not a feature (previous thing was with modcharts but yeah)

**Comment by flowerbearttv** [comment]
Thats cool, honestly wish there was documentation for some of the things you added to the lua handler. Or if there is, where is it?

**Comment by Leather128** [comment]
yea i need to make some docs for it since the docs that used to have it (old kade docs lol) aren't up anymore
