### ISSUE TITLE
Bug Report: When i enter pause menu it crashes

### ISSUE THREAD

**Issue by TristanTheCoderModder** [Leather128/LeatherEngine#91]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.

**Comment by TristanTheCoderModder** [comment]
Everytime i am playing Leather engine with mods and try to exit a song with pause menu it crashes

**Comment by TristanTheCoderModder** [comment]
Its just a problem with the mod i guess

**Comment by Leather128** [comment]
what mod?

**Comment by TristanTheCoderModder** [comment]
My own

**Comment by TristanTheCoderModder** [comment]
For some reason it works now when i fix the mod with the template mod-

**Comment by Leather128** [comment]
weird but aight
