### ISSUE TITLE
Enhancement: Move all ratings to the right when playing as opponent

### ISSUE THREAD

**Issue by Onemario1234** [Leather128/LeatherEngine#93]
Because at the moment, it kinda blocks incoming notes.
![image](https://user-images.githubusercontent.com/25996506/146733655-23e37039-ea7a-419b-a07e-673f0f15f4c5.png)

**Comment by Leather128** [comment]
oh that makes sense lol

**Comment by Leather128** [comment]
added in commit fa21e55
