### ISSUE TITLE
Question: When i try to build the game the application crashes

### ISSUE THREAD

**Issue by NeonixGithubMan** [Leather128/LeatherEngine#94]
I tried reinstalling polymod but it does not work! I tried updating polymod does not work either I do not know what I'm doing wrong

**Comment by Leather128** [comment]
could you give a list of the haxelib librarys you have installed (and their versions) which can be accessed with `haxelib list` in the cmd/terminal.

**Comment by NeonixGithubMan** [comment]
ok
list here
     I
     I
     V
actuate: [1.8.9]
box2d: [1.2.3]
discord_rpc: [git]
extension-webm: [git]
faxe: [git]
flixel-addons: [2.11.0] git
flixel-demos: [2.8.0]
flixel-templates: [2.6.6]
flixel-tools: [1.5.1]
flixel-ui: [2.4.0]
flixel: 4.8.1 [4.10.0]
hscript: [2.4.0]
hxcpp: [4.2.1]
hxvm-luajit: [git]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: 7.8.0 [7.9.0]
linc_luajit: [0.0.4]
newgrounds: [1.1.5]
openfl-samples: [8.7.0]
openfl-webm: [0.0.4]
openfl: [9.1.0]
polymod: [1.3.1]
systools: [1.1.0]

**Comment by Leather128** [comment]
try running `haxelib update` since some of your stuff is outdated on LE does use the most recent versions of stuff, so using the older versions may cause problems.

**Comment by NeonixGithubMan** [comment]
ok

**Comment by NeonixGithubMan** [comment]
i tried updating it but does not work!

**Comment by Leather128** [comment]
and you're running a 64 bit computer right? (if not, you have to take some extra steps to build 32 bit without it crashing)

**Comment by NeonixGithubMan** [comment]
I'm running a 64 bit computer

**Comment by Leather128** [comment]
and other versions of fnf build fine?

**Comment by NeonixGithubMan** [comment]
yes

**Comment by NeonixGithubMan** [comment]
they are fine

**Comment by NeonixGithubMan** [comment]
hello?

**Comment by Leather128** [comment]
question: you have tried using release builds of the game right?

**Comment by NeonixGithubMan** [comment]
i havent

**Comment by NeonixGithubMan** [comment]
I haven't tried releasing builds of the game

**Comment by Leather128** [comment]
OH

**Comment by Leather128** [comment]
i just realized

**Comment by Leather128** [comment]
can you try updating the flixel package from 4.8.1? because LE doesn't fully support flixel versions below 4.9.0
