### ISSUE TITLE
Bug Report: When I have a mod installed and try to go to the pause menu it crashes.

### ISSUE THREAD

**Issue by TristanTheCoderModder** [Leather128/LeatherEngine#98]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by TristanTheCoderModder** [comment]
I only have Characters in a mod i'm working on and everytime i hit enter with a character from the mod loaded it crashes.

**Comment by TristanTheCoderModder** [comment]
and i have the newest version/ 4.0.3 (dont really know the numbers but it is the newest version)

**Comment by Leather128** [comment]
are you running 64 bit or 32 bit?

**Comment by TristanTheCoderModder** [comment]
64 bit

**Comment by Leather128** [comment]
and this only happens when a specific mod is loaded?
